### ISSUE TITLE
when compile have some errors

### ISSUE THREAD

**Issue by geotyper** [mworchel/fluid-2d#1]
[ 11%] Building NVCC (Device) object CMakeFiles/fluid-2d-app.dir/src/fluid-2d-app_generated_velocity_grid_renderer.cu.o
/home/geo/CPP_sim_fluid/fluid-2d/src/linear_buffer.hpp(15): error: argument list for class template "gpu_buffer" is missing

/home/geo/CPP_sim_fluid/fluid-2d/src/linear_buffer.hpp(15): error: too many initializer values

/home/geo/CPP_sim_fluid/fluid-2d/src/linear_buffer.hpp(16): error: no default constructor exists for class "gpu_buffer<sf_line>"
          detected during instantiation of "linear_buffer<T>::linear_buffer(size_t, size_t) [with T=sf_line]" 
/home/geo/CPP_sim_fluid/fluid-2d/src/velocity_grid_renderer.cu(48): here

/home/geo/CPP_sim_fluid/fluid-2d/src/linear_buffer.hpp(45): error: identifier "width" is undefined
          detected during instantiation of "linear_buffer<T>::linear_buffer(size_t, size_t) [with T=sf_line]" 
/home/geo/CPP_sim_fluid/fluid-2d/src/velocity_grid_renderer.cu(48): here

/home/geo/CPP_sim_fluid/fluid-2d/src/linear_buffer.hpp(45): error: identifier "height" is undefined
          detected during instantiation of "linear_buffer<T>::linear_buffer(size_t, size_t) [with T=sf_line]" 
/home/geo/CPP_sim_fluid/fluid-2d/src/velocity_grid_renderer.cu(48): here

/home/geo/CPP_sim_fluid/fluid-2d/src/linear_buffer.hpp(41): error: identifier "width" is undefined
          detected during instantiation of "linear_buffer<T>::linear_buffer(size_t, size_t) [with T=sf_line]" 
/home/geo/CPP_sim_fluid/fluid-2d/src/velocity_grid_renderer.cu(48): here

/home/geo/CPP_sim_fluid/fluid-2d/src/linear_buffer.hpp(37): error: identifier "width" is undefined

/home/geo/CPP_sim_fluid/fluid-2d/src/linear_buffer.hpp(16): error: no default constructor exists for class "gpu_buffer<float>"
          detected during instantiation of "linear_buffer<T>::linear_buffer(size_t, size_t) [with T=float]" 
/home/geo/CPP_sim_fluid/fluid-2d/src/velocity_grid_renderer.cu(49): here

**Comment by geotyper** [comment]
Do you compile this project without this errors?

**Comment by mworchel** [comment]
Hi,

which CUDA and SFML versions do you use?

**Comment by geotyper** [comment]
CUDA 10.1 and  SFML 2.5.1

**Comment by mworchel** [comment]
Sorry for the late reply. I was only now able to test the code on a linux system. I pushed some changes. Can you see if they fix your errors?

**Comment by geotyper** [comment]
Thanks, now it works.
I change cmakelists.txt, but its minor changes:

cmake_minimum_required(VERSION 3.9 FATAL_ERROR)

```
project(fluid_2d LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(EXECUTABLE_NAME "fluid_2d")

find_package(SFML 2.5.1 COMPONENTS graphics)
set (INCLUDES ${INCLUDES} ${SFML_INCLUDE_DIRS})
set (LIBS ${LIBS} ${SFML_LIBRARIES})

include_directories(${INCLUDE_SDIR})
link_directories(${INCLUDE_SDIR})

set(APP_FILES "src/app.cpp"
              "src/app.hpp"
              "src/density_grid_renderer.cu"
              "src/density_grid_renderer.cuh"
              "src/fluid_solver.hpp"
              "src/fluid_solver_cpu.cpp"
              "src/fluid_solver_cpu.hpp"
              "src/fluid_solver_gpu.cu"
              "src/fluid_solver_gpu.cuh"
              "src/gpu_buffer.hpp"
              "src/grid.hpp"
              "src/grid_renderer.cpp"
              "src/grid_renderer.hpp"
              "src/kernel_launcher.hpp"
              "src/linear_buffer.hpp"
              "src/main.cpp"
              "src/pitched_buffer.hpp"
              "src/simulation.cpp"
              "src/simulation.hpp"
              "src/utilities.hpp"
              "src/velocity_grid_renderer.cu"
              "src/velocity_grid_renderer.cuh"
              ) 

find_package(CUDA REQUIRED)

set(
  CUDA_NVCC_FLAGS
  ${CUDA_NVCC_FLAGS};
  -O3 -gencode arch=compute_61,code=sm_61
 )

cuda_add_executable(${EXECUTABLE_NAME} ${APP_FILES})
target_link_libraries(${EXECUTABLE_NAME} sfml-graphics)
```

**Comment by mworchel** [comment]
Nice! Using CUDA with `find_package` is the "old" way of including CUDA, but I'm glad it worked for you.
